apiVersion: apps/v1
kind: Deployment
metadata:
  name: video processiog
  labels:
    app: video processiog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video processiog
  template:
    metadata:
      labels:
        app: video processiog
    spec:
      containers:
        - name: video processiog
          image: username/video processiog:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5